services:
  - type: web
    name: toupatou-backend
    runtime: node
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: toupatou-db
          property: connectionString

databases:
  - name: toupatou-db
    plan: free
